import { useEffect, useState } from 'react';
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import TopTrending from '@/components/TopTrending'
import TopCoins from '@/components/TopCoins';
import TopNews from '@/components/TopNews';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [trending, setTrending] = useState([]);
  const [topCoins, setTopCoins] = useState([]);
  const [news, setNews] = useState([]);
  const [trendingLoading, setTrendingLoading] = useState(false);
  const [topCoinsLoading, setTopCoinsLoading] = useState(false);
  const [newsLoading, setNewsLoading] = useState(false);

  useEffect(() => {

    const fetchTrending = async () => {
        setTrendingLoading(true);
        const res = await fetch(`https://api.coingecko.com/api/v3/search/trending`);
        const data = await res.json();
        setTrending(data?.coins);
        setTrendingLoading(false);
    }

    return () => {
        fetchTrending();
    }

}, []);

  useEffect(() => {

    const fetchTopCoins = async () => {
        setTopCoinsLoading(true);
        const res = await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=true`);
        const data = await res.json();
        setTopCoins(data);
        setTopCoinsLoading(false);
    }

    return () => {
        fetchTopCoins();
    }

}, []);

useEffect(() => {

  const fetchNews = async () => {
    try {
        setNewsLoading(true);
        const res = await fetch(`https://newsdata.io/api/1/crypto?apikey=pub_19290a585834877a948e9db9cc26be6be4d3b`);
        const data = await res.json();
        setNews(data?.data);
      } catch(error) {
        console.error(error);
        console.log('error occured fetching news: ', error);
      } 
      setNewsLoading(false);
  }

  return () => {
    fetchNews();
  }

}, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopCoins topCoins={topCoins} loading={topCoinsLoading}/>
      </main>
    </>
  )
}
